server:
  host: "0.0.0.0"
  port: "8080"

database:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  name: "${DB_NAME}"
  ssl_mode: "require"

jwt:
  secret: "${JWT_SECRET}"

app:
  environment: "production"
  log_level: "info"
  debug: false
